### ISSUE TITLE
Committing binaries

### ISSUE THREAD

**Issue by gitonthescene** [towbes/c_modernapproach#1]
Hey,

Doug from HN here.  Feel free to tell me to buzz off, but do you need to commit the binaries?   I think it’s not common practice since binaries are platform specific.  Given this the binaries end up cluttering the source directories.  Even when distributing binaries, it’s generally a good idea to keep them separate from the code.

My two cents,
Doug

**Comment by towbes** [comment]
No that's a good call I thought they were in the .gitignore but I guess they are not. I'll look into getting those out of here

**Comment by gitonthescene** [comment]
You might want to build the binaries in a separate directory from the source directory.  You could do this with a simple Makefile (if you're using *nix).  If you want a cross-platform build, you could use CMake (which I know much less about).  I'm guessing your focus is more on the language details but I thought I'd offer these pointers anyway.

**Comment by towbes** [comment]
Cleaned em up in this repository!  I'll have to do the same in my ThreePieces one as well.  Thanks for pointing this out early! They all have to be removed one by one.  Now I know for the future!
